# Default reveal.js configuration.
# See https://github.com/hakimel/reveal.js#configuration
revealjs_controls: true
revealjs_controlsTutorial: true
revealjs_controlsLayout: 'bottom-right'
revealjs_controlsBackArrows: 'faded'
revealjs_progress: true
revealjs_slideNumber: false
revealjs_hash: false
revealjs_history: false
revealjs_keyboard: true
revealjs_overview: true
revealjs_center: true
revealjs_touch: true
revealjs_loop: false
revealjs_rtl: false
revealjs_navigationMode: 'default'
revealjs_shuffle: false
revealjs_fragments: true
revealjs_fragmentInURL: false
revealjs_embedded: false
revealjs_help: true
revealjs_showNotes: false
revealjs_autoPlayMedia: null
revealjs_preloadIframes: null
revealjs_autoSlide: 0
revealjs_autoSlideStoppable: true
revealjs_autoSlideMethod: 'Reveal.navigateNext'
revealjs_defaultTiming: 120
revealjs_mouseWheel: false
revealjs_hideInactiveCursor: true
revealjs_hideCursorTime: 5000
revealjs_hideAddressBar: true
revealjs_previewLinks: false
revealjs_transition: 'slide'
revealjs_transitionSpeed: 'default'
revealjs_backgroundTransition: 'fade'
revealjs_viewDistance: 3
revealjs_parallaxBackgroundImage: ''
revealjs_parallaxBackgroundSize: ''
revealjs_parallaxBackgroundHorizontal: null
revealjs_parallaxBackgroundVertical: null
revealjs_display: 'block'
